version: "3.4"
services:
  postgres:
    container_name: Easybuydb
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ankit
        POSTGRES_DB: easybuydb
        POSTGRES_PASSWORD: ankitrawat
    
volumes:
  postgres_data: